spring.application.name=mgr-s22596
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mgr-s22596
spring.jackson.default-property-inclusion=NON_NULL
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ArchiveFT;integratedSecurity=true;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB
aws.s3.bucketName=mgr
aws.s3.region=eu-central-1
aws.s3.accessKey=ACCESS_KEY
aws.s3.secretKey=SECRET_KEY
